//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Change
    {
        public Change()
        { }

        public Change(System.DateTime _ChangeDate, string _ChangeType, string _ChangeFrom, string _ChangeTo)
        {
            ChangeDate = _ChangeDate;
            ChangeType = _ChangeType;
            ChangeFrom = _ChangeFrom;
            ChangeTo = _ChangeTo;
        }

        public int Id { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public string ChangeType { get; set; }
        public string ChangeFrom { get; set; }
        public string ChangeTo { get; set; }
    }
}
